title:             ACE Cash Express
email:             customerservice@acecashexpress.com
description:       Ace Cash Express
author:            Ace Cash Express
baseurl:           ""
url:               "https://50.acecashexpress.com"

# Social Profiles
twitter_username:  SBootstrap
github_username:   AceCashExpress
facebook_username: acecashexpress

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
